[build]
  command = "npm install && npm run build"
  publish = "."
  functions = "netlify/functions"
  ignore_python = true

[dev]
  framework = "#static"
  targetPort = 8888
  functionsPort = 3999
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios", "cheerio", "redis"]

[context.production.environment]
  NODE_VERSION = "18"